[build]
builder = "DOCKERFILE"
dockerfilePath = "infra/Dockerfile.postgres"
watchPatterns = ["infra/**"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
requiredMountPath = "/var/lib/postgresql/data"

[deploy.env]
PORT = "5432"

