[build]
builder = "RAILPACK"
buildCommand = "bun run build"
watchPatterns = ["apps/server/**", "packages/**"]

[deploy]
startCommand = "bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

healthcheckTimeout = 300
numReplicas = 1
