[build]
builder = "NIXPACKS"
buildCommand = "bun install && bun run build"
watchPatterns = ["apps/client/**", "packages/**"]

[deploy]
startCommand = "bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1
